/* Staff-only configuration: permissions are checked by every RPC. */
(() => {
 const host=document.querySelector('#vPraemien');if(!host)return;
 const controls=document.createElement('section');controls.className='card lp-admin-club';controls.innerHTML='<h2>Deinen Club gestalten</h2><p class="muted">Die Kundinnen sehen deine hinterlegten Prämien, Ränge und freigegebenen Ziele. Das nächste Prämienziel berechnet sich aus den Perlenkosten deiner Prämien.</p><div class="aktionen"><button type="button" class="btn ghost" data-nav="tMitt">Treueaktionen</button><button type="button" class="btn ghost" data-nav="tLevel">Ränge &amp; Vorteile</button><button type="button" class="btn ghost" data-nav="tAdvent">Advent &amp; Produktbilder</button><button type="button" class="btn ghost" data-goals>Behandlungsziele</button></div>';host.prepend(controls);
 controls.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{document.getElementById(b.dataset.nav)?.click();if(b.dataset.nav==='tMitt'){if(!document.getElementById('mTitel').value){document.getElementById('mBanner').value='true';document.getElementById('mMail').value='false';}document.getElementById('mTitel').focus();}});
 controls.querySelector('[data-goals]').onclick=()=>{box.scrollIntoView({block:'start'});box.querySelector('[data-load]').focus();};
 const box=document.createElement('section');box.className='card';box.style.marginTop='24px';
 box.innerHTML='<h2>Behandlungsziele</h2><p class="muted">Die fünf Fragen im Club sortieren deine freigegebenen Ziele nach Bereich, Etappenlänge und Geschenk. Kategorie, Anzahl und Abschlussprämie stellst du hier ein. Es werden keine Behandlungen aus Antworten erfunden.</p><p class="muted">Passende, gebuchte Behandlungen zählen höchstens einmal pro Tag. Eine Zielprämie wird pro Kundin und Ziel einmal freigeschaltet. Änderungen gelten für neu gestartete Ziele.</p><button class="btn" type="button" data-load>Ziele laden</button><div data-list></div><form hidden><h3 data-heading>Neues Ziel</h3><label>Zielname<input name="title" required maxlength="100" placeholder="Zum Beispiel: 5 × Intimlaser"></label><label>Passende Buchung<select name="category"><option value="laser_intim">Laser · Intim</option><option value="laser">Laser</option><option value="gesicht">Gesichtsbehandlung</option></select></label><label>Behandlungstage<input name="count" type="number" min="2" max="20" value="5" required></label><label>Abschlussprämie<select name="reward" required></select></label><label>Gültigkeit der Prämie in Tagen<input name="days" type="number" min="1" max="730" value="90" required></label><label><input name="active" type="checkbox"> Für Kundinnen freigeben</label><p><button class="btn" type="submit">Ziel speichern</button> <button class="btn ghost" data-new type="button">Neues Ziel</button></p></form><p data-status role="status"></p>';
 box.id='missionSettings';host.append(box);let selected=null,items=[];const form=box.querySelector('form'),status=box.querySelector('[data-status]');
 async function load(){try{const d=await rpc('admin_missionen',{p_token:session.token});items=d.vorlagen;const select=form.elements.reward;select.replaceChildren();for(const p of d.praemien){const o=document.createElement('option');o.value=p.id;o.textContent=p.bezeichnung;select.append(o);}const list=box.querySelector('[data-list]');list.replaceChildren();for(const v of items){const b=document.createElement('button');b.type='button';b.className='btn ghost';b.style.margin='8px 8px 8px 0';b.textContent=v.titel+(v.aktiv?' · aktiv':' · Entwurf');b.onclick=()=>edit(v);list.append(b);}form.hidden=false;status.textContent='';}catch(e){status.textContent=e.message;}}
 function edit(v){selected=v?.id||null;form.reset();if(v){form.elements.title.value=v.titel;form.elements.category.value=v.kategorie;form.elements.count.value=v.anzahl;form.elements.reward.value=v.praemie_id;form.elements.days.value=v.gueltigkeit_tage;form.elements.active.checked=v.aktiv;}box.querySelector('[data-heading]').textContent=v?'Ziel bearbeiten':'Neues Ziel';}
 box.querySelector('[data-load]').onclick=load;box.querySelector('[data-new]').onclick=()=>edit(null);
 form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('[type=submit]');b.disabled=true;try{await rpc('admin_mission_speichern',{p_token:session.token,p_id:selected,p_titel:form.elements.title.value,p_kategorie:form.elements.category.value,p_anzahl:+form.elements.count.value,p_praemie_id:form.elements.reward.value,p_aktiv:form.elements.active.checked,p_gueltigkeit_tage:+form.elements.days.value});await load();edit(null);status.textContent='Behandlungsziel gespeichert.';}catch(e){status.textContent=e.message;}finally{b.disabled=false;}};
})();
