begin;
do $$
declare k kundin; a jsonb; args jsonb; v jsonb; initial_tag text; claimed jsonb; old_version bigint;
begin
 perform selbst_registrieren('Wallet','Update','qa-wallet-update@example.invalid',current_setting('lp.qa_studio'),'de',null);
 select * into k from kundin where email='qa-wallet-update@example.invalid';
 update kundin set status='aktiv',email_bestaetigt_am=now() where id=k.id;
 update einstellung set wert='true' where schluessel in ('apple_wallet_aktiv','wallet_aktiv');
 update einstellung set wert='https://club.example.org/' where schluessel='club_basis_url';
 a:=wallet_apple_kartendaten(k.zugangstoken);
 assert length(a->>'auth_token')>=16,'Missing stable pass token';
 assert a->>'auth_token'<>k.zugangstoken,'Pass token must be separate';
 args:=jsonb_build_object('pass_type',a->>'pass_type','serial',a->>'object_id','token',a->>'auth_token','device_id','qa-device','push_token','qa-push');
 assert wallet_apple_service('register',args||'{"token":"wrong"}') is null,'Bad auth accepted';
 assert (wallet_apple_service('register',args)->>'created')::boolean,'Registration not created';
 assert not (wallet_apple_service('register',args)->>'created')::boolean,'Duplicate registration';
 v:=wallet_apple_service('list',args);initial_tag:=v->>'lastUpdated';
 assert jsonb_array_length(v->'serialNumbers')=1,'Wrong device pass list';
 assert wallet_apple_service('list',args||jsonb_build_object('since',initial_tag)) is null,'Unchanged pass returned';
 assert wallet_apple_service('list',args||'{"device_id":"stranger"}') is null,'Cross-device data leaked';
 insert into punktebewegung(organisation_id,kundin_id,betrag,anlass) values(k.organisation_id,k.id,100,'aktion');
 v:=wallet_apple_service('list',args||jsonb_build_object('since',initial_tag));
 assert (v->>'lastUpdated')::bigint>initial_tag::bigint,'Booking did not advance update tag';
 assert (wallet_apple_service('pass',args)->>'stand')::int=(select stand from punktekonto where kundin_id=k.id),'Pass has stale balance';
 select x into claimed from jsonb_array_elements(wallet_apple_service('claim','{}')) x where x->>'object_id'=a->>'object_id';
 assert claimed is not null,'Changed registered pass not claimed';
 assert not exists(select 1 from jsonb_array_elements(wallet_apple_service('claim','{}')) x where x->>'object_id'=a->>'object_id'),'Lease ignored';
 old_version:=(claimed->>'version')::bigint;
 insert into punktebewegung(organisation_id,kundin_id,betrag,anlass) values(k.organisation_id,k.id,25,'aktion');
 perform wallet_quittieren(jsonb_build_array(claimed||'{"ok":true}'));
 assert (select stand_version>quittiert_version from wallet_pass where serien_nummer=a->>'object_id'),'Concurrent update lost';
 perform wallet_apple_service('register',args||'{"push_token":"new-push"}');
 perform wallet_apple_service('invalid_device',args);
 assert exists(select 1 from wallet_apple_registration where device_id='qa-device'),'Old APNs reply deleted new token';
 perform wallet_apple_service('unregister',args);
 assert not exists(select 1 from wallet_apple_registration where device_id='qa-device'),'Unregister failed';
 -- Google must transmit the current name after an edit, using the same queue.
 a:=wallet_kartendaten(k.zugangstoken);
 perform wallet_gespeichert(k.zugangstoken);
 update kundin set vorname='Aktueller',nachname='Name' where id=k.id;
 select x into v from jsonb_array_elements(wallet_offene_karten(50)) x where x->>'object_id'=a->>'object_id';
 assert v->>'vorname'='Aktueller' and v->>'nachname'='Name','Google holder name stale or missing';
 update einstellung set wert='false' where schluessel in ('apple_wallet_aktiv','wallet_aktiv');
 assert wallet_apple_service('claim','{}')='[]'::jsonb,'Apple activation gate ignored';
 assert wallet_offene_karten(50)='[]'::jsonb,'Google activation gate ignored';
 assert not has_function_privilege('anon','wallet_apple_service(text,jsonb)','execute'),'Public service RPC';
 assert not has_table_privilege('anon','wallet_apple_registration','select'),'Public devices';
end $$;
select 'PASS Apple registrations, auth, update tags, balance, leases, concurrent changes, cleanup, activation gates and permissions' as result;
rollback;
